export const UPDATE_ACTIVE_ROUTE = 'UPDATE_ACTIVE_ROUTE';
export const CHANGE_NOTIFICATION_HOLDER = 'CHANGE_NOTIFICATION_HOLDER';
export const CHANGE_LATITUDE = 'CHANGE_LATITUDE';
export const CHANGE_LONGITUDE = 'CHANGE_LONGITUDE';
export const TWILLIO_CLIENT = 'TWILLIO_CLIENT';
export const CHECK_ONLINE_CLASS_VISIBILITY = 'CHECK_ONLINE_CLASS_VISIBILITY';
export const SDK_INITIALIZE = 'SDK_INITIALIZE';
export const CHECK_ENROLL_STATUS = 'CHECK_ENROLL_STATUS';
export const CHANGE_ONESIGNAL_USERID = 'CHANGE_ONESIGNAL_USERID';
export const FETCH_ENDPOINT = 'FETCH_ENDPOINT';
export const FETCH_ONLINE_CLASSES = 'FETCH_ONLINE_CLASSES';
export const FETCH_OFFLINE_CLASSES = 'FETCH_OFFLINE_CLASSES';
export const FETCH_TRAINER = 'FETCH_TRAINER';
export const REVIEW_ITEM = 'REVIEW_ITEM';
export const CHANGE_PLATFORM = 'CHANGE_PLATFOTM';
export const MODAL_VISIBILITY = 'MODAL_VISIBILITY';
export const CHECK_CORPORATE_STATE = 'CHECK_CORPORATE_STATE';
export const SET_CORPORATE_NAME = 'SET_CORPORATE_NAME';
export const CHECK_GUEST_USER = 'CHECK_GUEST_USER';
export const CHECK_SUBSCRIPTION_STATE = 'CHECK_SUBSCRIPTION_STATE';
export const GUEST_USER_NAVIGATION_PARAMS = 'GUEST_USER_NAVIGATION_PARAMS';
export const HOME_BACK_BUTTON = 'HOME_BACK_BUTTON';

export const LOADING = 'LOADING';

